; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=aarch64-unknown-linux-gnu -mattr=+sve | FileCheck %s --check-prefixes=CHECK-SVE

define i8 @test_v8i8_and(<8 x i8> %a) {
; CHECK-SVE-LABEL: test_v8i8_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.b, vl8
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    andv b0, p0, z0.b
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i8 @llvm.vector.reduce.and(<8 x i8> %a)
  ret i8 %r
}

define i8 @test_v16i8_and(<16 x i8> %a) {
; CHECK-SVE-LABEL: test_v16i8_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.b, vl16
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    andv b0, p0, z0.b
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i8 @llvm.vector.reduce.and(<16 x i8> %a)
  ret i8 %r
}

define i16 @test_v4i16_and(<4 x i16> %a) {
; CHECK-SVE-LABEL: test_v4i16_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.h, vl4
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    andv h0, p0, z0.h
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i16 @llvm.vector.reduce.and(<4 x i16> %a)
  ret i16 %r
}

define i16 @test_v8i16_and(<8 x i16> %a) {
; CHECK-SVE-LABEL: test_v8i16_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.h, vl8
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    andv h0, p0, z0.h
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i16 @llvm.vector.reduce.and(<8 x i16> %a)
  ret i16 %r
}

define i32 @test_v2i32_and(<2 x i32> %a) {
; CHECK-SVE-LABEL: test_v2i32_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s, vl2
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    andv s0, p0, z0.s
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i32 @llvm.vector.reduce.and(<2 x i32> %a)
  ret i32 %r
}

define i32 @test_v4i32_and(<4 x i32> %a) {
; CHECK-SVE-LABEL: test_v4i32_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    andv s0, p0, z0.s
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i32 @llvm.vector.reduce.and(<4 x i32> %a)
  ret i32 %r
}

define i64 @test_v1i64_and(<1 x i64> %a) {
; CHECK-SVE-LABEL: test_v1i64_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SVE-NEXT:    fmov x0, d0
; CHECK-SVE-NEXT:    ret
  %r = call i64 @llvm.vector.reduce.and(<1 x i64> %a)
  ret i64 %r
}

define i64 @test_v2i64_and(<2 x i64> %a) {
; CHECK-SVE-LABEL: test_v2i64_and:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d, vl2
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    andv d0, p0, z0.d
; CHECK-SVE-NEXT:    fmov x0, d0
; CHECK-SVE-NEXT:    ret
  %r = call i64 @llvm.vector.reduce.and(<2 x i64> %a)
  ret i64 %r
}

define i8 @test_v8i8_or(<8 x i8> %a) {
; CHECK-SVE-LABEL: test_v8i8_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.b, vl8
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    orv b0, p0, z0.b
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i8 @llvm.vector.reduce.or(<8 x i8> %a)
  ret i8 %r
}

define i8 @test_v16i8_or(<16 x i8> %a) {
; CHECK-SVE-LABEL: test_v16i8_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.b, vl16
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    orv b0, p0, z0.b
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i8 @llvm.vector.reduce.or(<16 x i8> %a)
  ret i8 %r
}

define i16 @test_v4i16_or(<4 x i16> %a) {
; CHECK-SVE-LABEL: test_v4i16_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.h, vl4
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    orv h0, p0, z0.h
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i16 @llvm.vector.reduce.or(<4 x i16> %a)
  ret i16 %r
}

define i16 @test_v8i16_or(<8 x i16> %a) {
; CHECK-SVE-LABEL: test_v8i16_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.h, vl8
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    orv h0, p0, z0.h
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i16 @llvm.vector.reduce.or(<8 x i16> %a)
  ret i16 %r
}

define i32 @test_v2i32_or(<2 x i32> %a) {
; CHECK-SVE-LABEL: test_v2i32_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s, vl2
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    orv s0, p0, z0.s
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i32 @llvm.vector.reduce.or(<2 x i32> %a)
  ret i32 %r
}

define i32 @test_v4i32_or(<4 x i32> %a) {
; CHECK-SVE-LABEL: test_v4i32_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    orv s0, p0, z0.s
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i32 @llvm.vector.reduce.or(<4 x i32> %a)
  ret i32 %r
}

define i64 @test_v1i64_or(<1 x i64> %a) {
; CHECK-SVE-LABEL: test_v1i64_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SVE-NEXT:    fmov x0, d0
; CHECK-SVE-NEXT:    ret
  %r = call i64 @llvm.vector.reduce.or(<1 x i64> %a)
  ret i64 %r
}

define i64 @test_v2i64_or(<2 x i64> %a) {
; CHECK-SVE-LABEL: test_v2i64_or:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d, vl2
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    orv d0, p0, z0.d
; CHECK-SVE-NEXT:    fmov x0, d0
; CHECK-SVE-NEXT:    ret
  %r = call i64 @llvm.vector.reduce.or(<2 x i64> %a)
  ret i64 %r
}

define i8 @test_v8i8_xor(<8 x i8> %a) {
; CHECK-SVE-LABEL: test_v8i8_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.b, vl8
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    eorv b0, p0, z0.b
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i8 @llvm.vector.reduce.xor(<8 x i8> %a)
  ret i8 %r
}

define i8 @test_v16i8_xor(<16 x i8> %a) {
; CHECK-SVE-LABEL: test_v16i8_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.b, vl16
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    eorv b0, p0, z0.b
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i8 @llvm.vector.reduce.xor(<16 x i8> %a)
  ret i8 %r
}

define i16 @test_v4i16_xor(<4 x i16> %a) {
; CHECK-SVE-LABEL: test_v4i16_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.h, vl4
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    eorv h0, p0, z0.h
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i16 @llvm.vector.reduce.xor(<4 x i16> %a)
  ret i16 %r
}

define i16 @test_v8i16_xor(<8 x i16> %a) {
; CHECK-SVE-LABEL: test_v8i16_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.h, vl8
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    eorv h0, p0, z0.h
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i16 @llvm.vector.reduce.xor(<8 x i16> %a)
  ret i16 %r
}

define i32 @test_v2i32_xor(<2 x i32> %a) {
; CHECK-SVE-LABEL: test_v2i32_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s, vl2
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-SVE-NEXT:    eorv s0, p0, z0.s
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i32 @llvm.vector.reduce.xor(<2 x i32> %a)
  ret i32 %r
}

define i32 @test_v4i32_xor(<4 x i32> %a) {
; CHECK-SVE-LABEL: test_v4i32_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.s, vl4
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    eorv s0, p0, z0.s
; CHECK-SVE-NEXT:    fmov w0, s0
; CHECK-SVE-NEXT:    ret
  %r = call i32 @llvm.vector.reduce.xor(<4 x i32> %a)
  ret i32 %r
}

define i64 @test_v1i64_xor(<1 x i64> %a) {
; CHECK-SVE-LABEL: test_v1i64_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    // kill: def $d0 killed $d0 def $q0
; CHECK-SVE-NEXT:    fmov x0, d0
; CHECK-SVE-NEXT:    ret
  %r = call i64 @llvm.vector.reduce.xor(<1 x i64> %a)
  ret i64 %r
}

define i64 @test_v2i64_xor(<2 x i64> %a) {
; CHECK-SVE-LABEL: test_v2i64_xor:
; CHECK-SVE:       // %bb.0:
; CHECK-SVE-NEXT:    ptrue p0.d, vl2
; CHECK-SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-SVE-NEXT:    eorv d0, p0, z0.d
; CHECK-SVE-NEXT:    fmov x0, d0
; CHECK-SVE-NEXT:    ret
  %r = call i64 @llvm.vector.reduce.xor(<2 x i64> %a)
  ret i64 %r
}
