; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64--linux-gnu -mattr=+sve < %s | FileCheck %s

define <1 x i64> @cttz_1_i64(<1 x i64> %a) {
; CHECK-LABEL: cttz_1_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl1
; CHECK-NEXT:    // kill: def $d0 killed $d0 def $z0
; CHECK-NEXT:    clz z0.d, p0/m, z0.d
; CHECK-NEXT:    // kill: def $d0 killed $d0 killed $z0
; CHECK-NEXT:    ret
  %result = call <1 x i64> @llvm.ctlz(<1 x i64> %a, i1 0)
  ret <1 x i64> %result
}

define <2 x i64> @cttz_2_i64(<2 x i64> %a) {
; CHECK-LABEL: cttz_2_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ptrue p0.d, vl2
; CHECK-NEXT:    // kill: def $q0 killed $q0 def $z0
; CHECK-NEXT:    clz z0.d, p0/m, z0.d
; CHECK-NEXT:    // kill: def $q0 killed $q0 killed $z0
; CHECK-NEXT:    ret
  %result = call <2 x i64> @llvm.ctlz(<2 x i64> %a, i1 0)
  ret <2 x i64> %result
}
